package pkgEnum;

/**
 * Created by David on 20.01.2016.
 */
public enum ENUM_SERVICE {
    SERVICE_ADRESSE,
    SERVICE_HAUSHALT,
    SERVICE_MITGLIED,
    SERVICE_ORT,
    SERVICE_STRASSE,
    SERVICE_VERWALTUNGSPERSONAL,
    SERVICE_WASSERZAEHLER,
    SERVICE_WASSERSTANDSMELDUNG
}
